### ISSUE TITLE
How does python-fido2 library sign the data when sending make-credential request to the FIDO authenticator?

### ISSUE THREAD

**Issue by kimo6416337** [Yubico/python-fido2#152]
Hi!

I've met a signature verification problem on FIDO registration flow.
The scenario I build a FIDO flow is
1. I use the StrongKey FIDO server as my FIDO server. I ensure that the server is working well if using their own demo web site to do registration and authentication.
2. I write a python code to do FIDO registration with the python-fido2 library.
3. My authenticator is an external Yubico USB key.
4. The working flow is as below.
![image](https://user-images.githubusercontent.com/5336069/186112014-e23c624f-23f9-49b4-bbf3-361b92a9571f.png)

I also created another discussion thread in SKFS github. Please refer to [https://github.com/StrongKey/fido2/issues/201](https://github.com/StrongKey/fido2/issues/201).

I am wondering what data is signed to create the "sig" and "x5c" in the attStmt?
How can I create the corrent clientDataJSON and attestationObject to send to the FIDO server with the returned data of client.make_credential(create_options["publicKey"])?

Thanks

**Comment by dainnilsson** [comment]
I took a quick look at the linked thread. The issue about `crossOrigin` vs `cross_origin` is indeed a bug in this library, but it has been fixed in `main`. Another potential problem I see with the data you posted is this:

```user=PublicKeyCredentialUserEntity(name='johndoe', id=b'Bs3eUb4q_nz5xe93dLc50jnCMns6zu8ac8vx_6mSJjI', display_name=None), challenge=b'2yiG1m-DXiYfIEv8gf2Sgg', ```

The `challenge` field as well as the `user.id` field are displayed as raw byte strings, but the content looks like it is (websafe) base64 encoded. I'm guessing that you may be missing a decode step here, which would result in a double encoding that might cause the problems you're seeing as the challenge in the ClientDataJSON would not match the one that the server is expecting.

If you can provide the contents of the `create_options['publicKey']` which you are passing to `client.make_credential` I might be able to see what the issue is.

**Comment by kimo6416337** [comment]
@dainnilsson After using your solution, registration can be successful.
I send a base64-decoded challenge (from FIDO2 server) and user.id to make credential.
Create the clientDataJSON by using result.client_data.b64.
BTW, in fact, after checking the source code of python-fido2, I can directly send the challenge string to make credential without base64-decoding.
```
challenge=b'2yiG1m-DXiYfIEv8gf2Sgg'
```
This challenge is transformed to bytes type with the original challenge string. If sending this bytes-type challenge to make credential, then python-fido2 will base64-encode a bytes-type challenge.
