### ISSUE TITLE
Pin validation issue for latest fido2 1.0.0.0 library for preferred scenario

### ISSUE THREAD

**Issue by YashwanthLokam** [Yubico/python-fido2#153]
Hi,
   I am using the latest 1.0.0.0 fido2 library. I cannot find an method which accepts the pin entered by user. I am using get_assertion method in Fido2Client class. This method do not have an argument which accepts the pin. In the previous version, we have an option to pass pin to get_assertion(). I want to know which method should I use for pin validation in user_verification=preferred scenario.

**Comment by dainnilsson** [comment]
You need to pass a `UserInteraction` instance to the `Fido2Client`. Take a look at the included `examples`, for example https://github.com/Yubico/python-fido2/blob/main/examples/credential.py#L79 with its implementation here: https://github.com/Yubico/python-fido2/blob/main/examples/credential.py#L43

**Comment by YashwanthLokam** [comment]
Thank you, that worked. I just have one more question. Is it possible to do bio enroll with the latest 1.0 lib without using windows WebAuthnAPIs? If yes, do you have any example code or can you tell me which method to use.

**Comment by dainnilsson** [comment]
Yes it is possible, but do note that on Windows this requires running the process as Administrator. There is an example performing bio enroll here: https://github.com/Yubico/python-fido2/blob/main/examples/bio_enrollment.py

**Comment by YashwanthLokam** [comment]
Is it possible do to biometric authentication without the use of windows WebAuthnAPIs?

**Comment by dainnilsson** [comment]
Yes, but same thing there, it required running the process as Administrator. Doing anything on Windows without using the webauthn.h API's require Administrator. If you run the example https://github.com/Yubico/python-fido2/blob/main/examples/credential.py without being Administrator using a Security Key that supports it, it will use the built-in UV mechanism instead of prompting for a PIN to create, and authenticate, a credential.
