### ISSUE TITLE
fido2.cbor can not parse cbor-web output

### ISSUE THREAD

**Issue by PhilippSiegmantel** [Yubico/python-fido2#157]
Hello!

We recently wanted to replace our old and unmaintained frontend cbor implementation with [cbor-web](https://www.npmjs.com/package/cbor-web). Sadly, fido2.cbor is unable to parse its output, even if cbor-web is configured to not include its metadata.
All is fine and well when we replace fido2.cbor with [cbor2](https://pypi.org/project/cbor2/), but in the interest of keeping our Pipfile lean, I wanted to ask whether there are any plans to extend difo2.cbor?

**Comment by dainnilsson** [comment]
We don't have plans to extend fido2.cbor beyond what is required by the library itself. That said, I'd be interested in what is missing that cbor-web is using.

On a different note, I'd also be interested in what you are using CBOR on the client side for. If it's only for (de-)serialization of the WebAuthn data types, then you may want to consider using JSON for this instead. See #146 for details. Our server example (https://github.com/Yubico/python-fido2/tree/main/examples/server) has been updated on `main` to use this instead of CBOR.

This functionality will be included in python-fido2 1.1 which is planned to be released in October.

**Comment by dainnilsson** [comment]
Closing due to lack of response, please re-open or comment if there is more to discuss.
