### ISSUE TITLE
Encoding of create_options

### ISSUE THREAD

**Issue by the2nd** [Yubico/python-fido2#169]
When generating the create_options on server side with:
create_options, state = server.register_begin(user, user_verification=uv, authenticator_attachment=authenticator_attachment)

The create_options (public key) must be transmitted from the server to the client. Whats the preferred way of doing this? Is there any method do encode create_options for transmission over the network?

**Comment by dainnilsson** [comment]
Initially this was left fully to the implementer, but a more JSON-friendly format has been proposed that takes care of encoding the binary fields. python-fido2 added support for this in version 1.1, but it requires explicit opt-in since it changes the existing behavior (in version 2.0 this opt-in will no longer be required, the new behavior will replace the old). You can see an example of this in the server example code: https://github.com/Yubico/python-fido2/blob/main/examples/server/server/server.py#L43

Once enabled, calling `dict(create_options)` will give you a json-serializable dict that you can send to the client. More details on the format can be seen here: https://github.com/w3c/webauthn/issues/1683

Note that the API for deserializing on the client side isn't broadly supported at the moment, but can be achieved using a small JS library: https://github.com/github/webauthn-json which is what the server example uses here, for example: https://github.com/Yubico/python-fido2/blob/main/examples/server/server/static/register.html#L16

**Comment by the2nd** [comment]
> Initially this was left fully to the implementer, but a more JSON-friendly format has been proposed that takes care of encoding the binary fields. python-fido2 added support for this in version 1.1, but it requires explicit opt-in since it changes the existing behavior (in version 2.0 this opt-in will no longer be required, the new behavior will replace the old). You can see an example of this in the server example code: https://github.com/Yubico/python-fido2/blob/main/examples/server/server/server.py#L43
> 
> Once enabled, calling `dict(create_options)` will give you a json-serializable dict that you can send to the client. More details on the format can be seen here: [w3c/webauthn#1683](https://github.com/w3c/webauthn/issues/1683)
> 
> Note that the API for deserializing on the client side isn't broadly supported at the moment, but can be achieved using a small JS library: https://github.com/github/webauthn-json which is what the server example uses here, for example: https://github.com/Yubico/python-fido2/blob/main/examples/server/server/static/register.html#L16

Thanks this is a good step forward. But as my authentication server uses python on both, server and client, having a json-deserializing method in python-fido2 would be really great.

And also i wonder how to serialize client_data and attestation_object used by server.register_complete() and the other objects that are required for authentication like in this example: https://github.com/Yubico/python-fido2/blob/main/examples/credential.py
