### ISSUE TITLE
<class 'OverflowError'>exception during authentication

### ISSUE THREAD

**Issue by YashwanthLokam** [Yubico/python-fido2#178]
Hi, I am getting this exception **argument 1: <class 'OverflowError'>: int too long to convert** when I am trying to check if key is available or not. This error pops up mostly in VM ware. Error occurs at next(CtapHidDevice.list_devices(), None) function.

**Comment by PranithaReddyAedla** [comment]
@dainnilsson Could we get any update here please?

**Comment by dainnilsson** [comment]
Please provide more information. Full traceback, Operating system, authenticator device type, etc.

**Comment by PranithaReddyAedla** [comment]
@dainnilsson
1. There is no stack trace, we are only getting the mentioned string.

**Comment by PranithaReddyAedla** [comment]
@dainnilsson 
1. We dont have stack trace, we have just got mentioned message (**<class 'OverflowError'>: int too long to convert**) and sometimes "**Wrong nonce**" while checking if security key if connected to machine using next(CtapHidDevice.list_devices(), None) function.
2. OS: Windows 10/11
3. Authenticator Device type : Yubikey 5 NFC and Yubikey 4 NFC.
4. [python-fido2](https://github.com/Yubico/python-fido2) version : v0.9.1
We are using same logic and version from quiet some time but never faced any issue. Since past 1 or 2 months we are receiving these kind of errors from users.

**Comment by dainnilsson** [comment]
Without a stack trace it's hard to say anything definitive. The fact that you're getting the wrong nonce and that this happens when connecting to the device indicates that there might be a problem with multiple threads/processes trying to use the YubiKey concurrently. If you have more concrete steps that reproduce this issue I might be able to help more.

**Comment by YashwanthLokam** [comment]
@dainnilsson
I am sharing you a screenshot where I found the issue thrown as an Exception.
![image (16)](https://user-images.githubusercontent.com/73385194/230375913-23f82f4c-f49e-424c-a499-3b4639893cee.png)
