### ISSUE TITLE
Issue with Py2.7 Django

### ISSUE THREAD

**Issue by mkalioby** [Yubico/python-fido2#30]
I trying to integrating this repo with Django 1.8 on Python 2.7 and I getting this strange in object loaded in JS

**view.py**
registration_data, state = server.register_begin({
        'id': request.user.username,
        'name': request.user.first_name + " " + request.user.last_name,
        'displayName': request.user.username,
        'icon': settings.STATIC_URL + "img/favicon.ico"
    }, [])

 return HttpResponse(cbor.dumps(registration_data),content_type='application/octet-stream')

**JS Object received from begin_registeration**
![selection_351](https://user-images.githubusercontent.com/10414020/50902973-817c4680-142d-11e9-8068-e3c42339ed8f.png)

The problem that user dict keys are represented in binary so the navigator.credentials.create() fails as no username is provided.

**Comment by dainnilsson** [comment]
The problem here is the difference in string handling between Python 2 and 3. For the CBOR serialization to use the string type, the Python 2 key needs to be of the `unicode` type.

The `user` object in the registration data is the one you passed in, unmodified. If you change the keys in your *view.py* code to use unicode literals instead (eg. `u'name'` etc) then the return value should serialize correctly.
