### ISSUE TITLE
Touch ID is working

### ISSUE THREAD

**Issue by mkalioby** [Yubico/python-fido2#34]
Hi,

This isn't a bug, this is info that Touch ID on Macbook using Chrome 70 is working fine and it is recognized as  'packed'

**Comment by dainnilsson** [comment]
Great, good to hear.

**Comment by nsandhu-godaddy** [comment]
Is there an example of this? I can't seem to find any documentation around it. Can you please point me in the right direction?

**Comment by mkalioby** [comment]
Which web framework are you using?

**Comment by nabheet** [comment]
Sorry I deleted my previous comment because it was posted from a different account.

None. I wrote a CLI tool for our use case using Fido2Client and followed this example: https://github.com/Yubico/python-fido2/blob/main/examples/credential.py#L62

Oh! I see what you mean. You tried it in Chrome!!!! maybe our use cases are different?
