### ISSUE TITLE
Missing "alg" parameter in key agreement public key

### ISSUE THREAD

**Issue by andrewkozlik** [Yubico/python-fido2#67]
According to https://fidoalliance.org/specs/fido-v2.0-ps-20190130/fido-client-to-authenticator-protocol-v2.0-ps-20190130.html the COSE_Key-encoded public key MUST contain the optional "alg" parameter. However, the key agreement public key returned by PinProtocolV1::get_shared_secret() is missing the "alg" parameter, see
https://github.com/Yubico/python-fido2/blob/1021538414e08c7fa2a7b3f754148beb92c18801/fido2/ctap2.py#L802-L807

**Comment by dainnilsson** [comment]
This has been a deliberate choice as there is no valid value for "alg" which describes the actual key agreement scheme as specified. However, the latest draft of the CTAP2 spec has been amended with the following note:

> Note: The COSEAlgorithmIdentifier used is -25 (ECDH-ES + HKDF-256) although this is NOT the algorithm actually used. Setting this to a different value may result in compatibility issues.

Due to this amendment of the spec we will be adding the "alg" parameter going forward.
